#!/bin/bash


echo "Scaling Django app to 3 replicas..."
kubectl scale deployment messaging-app --replicas=3


echo "Waiting for pods to be ready..."
kubectl rollout status deployment messaging-app

# Verifying that multiple pods are running
echo "Verifying that multiple pods are running..."
kubectl get pods

# Performing load testing using wrk 
echo "Performing load testing with wrk..."

wrk -t12 -c400 -d30s http://<service-ip>:8080

# Monitoring resource usage (CPU and Memory)
echo "Monitoring resource usage..."
kubectl top pods

# Done
echo "Scaling operation and monitoring complete."
