apiVersion: v1
kind: Service
metadata:
  name: django-messaging-service
spec:
  selector:
    app: django-messaging-app
    version: blue  # Initially point to the blue version
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
